export const SKILLS_DATA: string[] = [
  // Teknologi & Pemrograman
  'JavaScript',
  'TypeScript',
  'React.js',
  'Next.js',
  'Node.js',
  'Express.js',
  'NestJS',
  'Vue.js',
  'Angular',
  'Svelte',
  'HTML',
  'CSS',
  'SCSS',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'Chakra UI',
  'Styled Components',
  'Redux',
  'Zustand',
  'GraphQL',
  'Apollo Client',
  'REST API',
  'WebSockets',
  'tRPC',
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'SQLite',
  'Prisma ORM',
  'Sequelize',
  'Mongoose',
  'Firebase',
  'Supabase',
  'Strapi',
  'Sanity.io',
  'WordPress',
  'PHP',
  'Laravel',
  'Python',
  'Django',
  'Flask',
  'FastAPI',
  'Ruby on Rails',
  'Go',
  'Rust',
  'Java',
  'Spring Boot',
  'Kotlin',
  'Swift',
  'Objective-C',
  'C',
  'C++',
  'C#',
  '.NET Core',
  'Unity',
  'Unreal Engine',
  'Docker',
  'Kubernetes',
  'Terraform',
  'AWS',
  'Azure',
  'Google Cloud',
  'Vercel',
  'Netlify',
  'Jenkins',
  'GitHub Actions',
  'CI/CD',
  'Linux',
  'Bash Scripting',
  'PowerShell',
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'WebRTC',
  'Three.js',
  'D3.js',
  'Electron.js',
  'Tauri',
  'Flutter',
  'React Native',
  'Ionic',
  'Expo',
  'Jest',
  'Mocha',
  'Chai',
  'Cypress',
  'Playwright',
  'Vitest',
  'Storybook',
  'Figma',
  'Adobe XD',
  'Photoshop',
  'Illustrator',
  'Canva',
  'Webflow',
  'Framer',
  'Scrum',
  'Kanban',
  'Agile',
  'JIRA',
  'Notion',
  'Trello',
  'Asana',
  'Slack',
  'ChatGPT API',
  'OpenAI API',
  'LangChain',
  'Machine Learning',
  'Data Science',
  'SQL',
  'NoSQL',
  'Cybersecurity',
  'Blockchain',
  'Smart Contracts',
  'Solidity',
  'Penetration Testing',
  'Reverse Engineering',
  'Ethical Hacking',
  'Cryptography',
  'DevOps',
  'Big Data',
  'Artificial Intelligence',
  'Deep Learning',
  'Computer Vision',
  'NLP',
  'Robotic Process Automation (RPA)',
  'Embedded Systems',
  'Internet of Things (IoT)',
  '3D Printing',
  'Game Development',
  'Shadcn UI',

  // Desain & Kreativitas
  'Adobe Photoshop',
  'Adobe Illustrator',
  'Adobe XD',
  'Figma',
  'Sketch',
  'Canva',
  'Webflow',
  'Framer',
  '3D Modeling',
  'Video Editing',
  'Motion Graphics',
  'UI/UX Design',
  'Branding',
  'Typography',
  'Color Theory',
  'Photography',
  'Animation',
  'Illustration',
  'Game Design',
  'Character Design',
  'Sound Design',
  'Interior Design',
  'Fashion Design',
  'Product Design',
  'Industrial Design',
  'Creative Writing',
  'Storyboarding',
  'Video Production',
  'Cinematography',
  'Visual Effects (VFX)',
  'Augmented Reality (AR)',
  'Virtual Reality (VR)',
  'Stop Motion Animation',
  'Digital Painting',

  // Bisnis & Manajemen
  'Project Management',
  'Product Management',
  'Scrum',
  'Agile',
  'Kanban',
  'Business Strategy',
  'Financial Analysis',
  'Market Research',
  'SEO',
  'Digital Marketing',
  'Social Media Marketing',
  'Affiliate Marketing',
  'E-commerce',
  'Sales',
  'Customer Service',
  'Public Relations',
  'Negotiation',
  'Leadership',
  'Entrepreneurship',
  'Time Management',
  'Risk Management',
  'Human Resources (HR)',
  'Recruitment',
  'Payroll Management',
  'Business Intelligence',
  'Data Analytics',
  'Investor Relations',
  'Supply Chain Management',
  'Operations Management',
  'Procurement',
  'Event Planning',
  'Brand Management',
  'Crisis Management',

  // Bahasa & Komunikasi
  'Copywriting',
  'Content Writing',
  'Technical Writing',
  'Public Speaking',
  'Storytelling',
  'Translation',
  'Interpersonal Communication',
  'Persuasion',
  'Editing & Proofreading',
  'Blogging',
  'Podcasting',
  'Sign Language',
  'Non-verbal Communication',
  'Crisis Communication',
  'Journalism',
  'Creative Writing',
  'Scriptwriting',
  'Ghostwriting',
  'Grant Writing',
  'Speechwriting',
  'Voice Acting',
  'Dubbing',
  'Customer Support',
  'Call Center Management',

  // Pendidikan & Pelatihan
  'Teaching',
  'Curriculum Development',
  'Training & Development',
  'Coaching',
  'Mentoring',
  'E-learning Development',
  'Instructional Design',
  'Academic Research',
  'Tutoring',
  'Early Childhood Education',
  'Special Education',
  'Educational Psychology',
  'Lesson Planning',

  // Sains & Kesehatan
  'Medical Research',
  'Nursing',
  'Pharmacy',
  'Physical Therapy',
  'Mental Health Counseling',
  'Nutrition',
  'Personal Training',
  'First Aid & CPR',
  'Public Health',
  'Biotechnology',
  'Genetics',
  'Environmental Science',
  'Bioinformatics',
  'Veterinary Science',
  'Epidemiology',
  'Pharmaceutical Manufacturing',
  'Medical Coding',
  'Medical Imaging',
  'Clinical Trials',

  // Industri & Kerajinan
  'Carpentry',
  'Metalworking',
  'Plumbing',
  'Electrical Work',
  'Automotive Repair',
  'Welding',
  'Masonry',
  'Furniture Design',
  'Painting & Coating',
  'Jewelry Making',
  'Textile Design',
  'Handmade Crafts',
  'Cooking',
  'Baking',
  'Bartending',
  'Gardening',
  'Floristry',
  'Candle Making',
  'Woodworking',
  'Sewing',
  'Leatherworking',
  'Blacksmithing',
  'Glassblowing',
  'Pottery',
  'Tile Installation',

  // Hobi & Keterampilan Lainnya
  'Chess',
  'Photography',
  'Videography',
  'Music Production',
  'Singing',
  'Dancing',
  'Acting',
  'Yoga',
  'Meditation',
  'Public Speaking',
  'Survival Skills',
  'Fishing',
  'Camping',
  'Travel Planning',
  'Investing',
  'Stock Trading',
  'Cryptocurrency Trading',
  'Astrology',
  'Numerology',
  'Feng Shui',
  'Scuba Diving',
  'Martial Arts',
  'Parkour',
  'Archery',
  'Horse Riding',
  'Rock Climbing',
  'Skydiving',
  'Paragliding',
  'Sailing',
  'Cycling',
  'Darts',
  'Calligraphy',
  'Origami',
  'Board Games',
  'Esports',
  'Magic Tricks',
  'Pet Training',
  'Beekeeping',
  'Mushroom Farming',
  'Composting',
];
